# Generated by Django 5.2.2 on 2025-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("created_time", models.DateField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=5000)),
            ],
        ),
    ]
