# Generated by Django 5.2.2 on 2025-06-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_dateTime", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=5000)),
                ("author_ip", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
