name: Github Ci
run-name: Tests by @${{ github.actor }} 🚀

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar variáveis de ambiente para testes
        run: |
          echo "DATABASE_NAME=test_db" >> $GITHUB_ENV
          echo "DATABASE_USER=postgres" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=123456" >> $GITHUB_ENV
          echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
          echo "DATABASE_PORT=5432" >> $GITHUB_ENV

      - name: Gerar migrações (com input automático)
        run: |
          echo "1" | python manage.py makemigrations || echo "Migrações podem já estar atualizadas"
        env:
          DATABASE_NAME: test_db
          DATABASE_USER: postgres
          DATABASE_PASSWORD: 123456
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432

      - name: Aplicar migrações  # ⬅️ MOVER ESTE PASSO PARA CIMA
        run: |
          python manage.py migrate
        env:
          DATABASE_NAME: test_db
          DATABASE_USER: postgres
          DATABASE_PASSWORD: 123456
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432

      - name: Rodar Horusec (Análise de Segurança)
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./