name: Github Ci
run-name: Tests by @${{ github.actor }} 🚀

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar verificações de código
        run: |
          echo "Rodando verificações de código..."
          python manage.py makemigrations --check --dry-run
        env:
          POSTGRES_PASSWORD: 123456
          DATABASE_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Rodar testes e cobertura de código
        run: pytest --cov=.
        env:
          POSTGRES_PASSWORD: 123456
          DATABASE_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Rodar Horusec (Análise de Segurança)
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./
